export enum ACTIONS {
    LOAD_RESPONSE_LIST_FETCHING = 'LOAD_RESPONSE_LIST_FETCHING',
    LOAD_RESPONSE_LIST_LOADED = 'LOAD_RESPONSE_LIST_LOADED',
    LOAD_RESPONSE_LIST_ERROR = 'LOAD_RESPONSE_LIST_ERROR',
    LOAD_QUESTIONNAIRE_FETCHING = 'LOAD_QUESTIONNAIRE_FETCHING',
    LOAD_QUESTIONNAIRE_LOADED = 'LOAD_QUESTIONNAIRE_LOADED',
    LOAD_QUESTIONNAIRE_ERROR = 'LOAD_QUESTIONNAIRE_ERROR',
}

export enum STATUS_RESPONSE_LIST_LOADING {
    fetching = 'fetching',
    loaded = 'loaded',
    error = 'error'
}

export enum STATUS_QUESTIONNAIRE_LOADING {
    fetching = 'fetching',
    loaded = 'loaded',
    error = 'error'
}