export const CREATE_QUESTIONNAIRE_RESPONSE = 'CREATE_QUESTIONNAIRE_RESPONSE';
export type CREATE_QUESTIONNAIRE_RESPONSE = typeof CREATE_QUESTIONNAIRE_RESPONSE;

export const UPDATE_QUESTIONNAIRE_RESPONSE = 'UPDATE_QUESTIONNAIRE_RESPONSE';
export type UPDATE_QUESTIONNAIRE_RESPONSE = typeof UPDATE_QUESTIONNAIRE_RESPONSE;

export const ADD_QUESTIONNAIRE_RESPONSE_ITEM = 'ADD_QUESTIONNAIRE_RESPONSE_ITEM';
export type ADD_QUESTIONNAIRE_RESPONSE_ITEM = typeof ADD_QUESTIONNAIRE_RESPONSE_ITEM;

export const UPDATE_QUESTIONNAIRE_RESPONSE_ITEM = 'UPDATE_QUESTIONNAIRE_RESPONSE_ITEM';
export type UPDATE_QUESTIONNAIRE_RESPONSE_ITEM = typeof UPDATE_QUESTIONNAIRE_RESPONSE_ITEM;

export type ACTION = CREATE_QUESTIONNAIRE_RESPONSE | UPDATE_QUESTIONNAIRE_RESPONSE | UPDATE_QUESTIONNAIRE_RESPONSE_ITEM | ADD_QUESTIONNAIRE_RESPONSE_ITEM;