export enum ACTIONS {
    LOAD_QUESTIONNAIRE_LIST_FETCHING = 'LOAD_QUESTIONNAIRE_LIST_FETCHING_QLP',
    LOAD_QUESTIONNAIRE_LIST_LOADED = 'LOAD_QUESTIONNAIRE_LIST_LOADED_QLP',
    LOAD_QUESTIONNAIRE_LIST_ERROR = 'LOAD_QUESTIONNAIRE_LIST_ERROR_QLP',
    DELETE_QUESTIONNAIRE_DELETING = 'DELETE_QUESTIONNAIRE_DELETING_QLP',
    DELETE_QUESTIONNAIRE_DELETED = 'DELETE_QUESTIONNAIRE_DELETED_QLP',
    DELETE_QUESTIONNAIRE_ERROR = 'DELETE_QUESTIONNAIRE_ERROR_QLP'
}

export enum STATUS_LOADING {
    fetching = 'fetching',
    loaded = 'loaded',
    error = 'error'
}

export enum STATUS_DELETING {
    deleting = 'deleting',
    deletingEnded = 'deletingEnded'
}