export const CREATE_QUESTIONNAIRE = 'CREATE_QUESTIONNAIRE';
export type CREATE_QUESTIONNAIRE = typeof CREATE_QUESTIONNAIRE;

export const SET_TITLE = 'SET_TITLE';
export type SET_TITLE = typeof SET_TITLE;

export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export type SET_DESCRIPTIONS = typeof SET_DESCRIPTION;

export const ADD_TEXT_ITEM = 'ADD_TEXT_ITEM';
export type ADD_TEXT_ITEM = typeof ADD_TEXT_ITEM;

export type QUESTIONNAIRE_ACTION = CREATE_QUESTIONNAIRE | SET_TITLE | SET_DESCRIPTIONS | ADD_TEXT_ITEM;